# It is the serverless configuration for Lambda of MPF Price Retrieval
#

service: mpf-price-service

# Resource

resources:
  Resources:
    mpfPriceQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:service}-mpf-price-queue-${self:provider.stage}
        VisibilityTimeout: 300
  Outputs:
    saveMPFPriceDynamodbArn:
      Export:
        Name: saveMPFPriceDynamodbArn
      Value:
         Fn::GetAtt: SaveMPFPriceDynamodbLambdaFunction.Arn
    retrieveMPFPriceArn:
      Export:
        Name: retrieveMPFPriceArn
      Value:
         Fn::GetAtt: RetrieveMPFPriceLambdaFunction.Arn

# Provider

provider:
  name: aws
  runtime: nodejs8.10

  stage: dev
  region: us-east-2

  timeout: 300

# the Lambda function's IAM Role
  iamRoleStatements:
    - Effect: "Allow"
      Action:
          - "sqs:DeleteMessage"
          - "sqs:GetQueueUrl"
          - "sqs:ChangeMessageVisibility"
          - "sqs:DeleteMessageBatch"
          - "sqs:SendMessageBatch"
          - "sqs:ReceiveMessage"
          - "sqs:SendMessage"
          - "sqs:GetQueueAttributes"
          - "sqs:ChangeMessageVisibilityBatch"
      Resource:
        Fn::GetAtt:
          - mpfPriceQueue
          - Arn
    - Effect: "Allow"
      Action:
          - "sqs:DeleteMessage"
          - "dynamodb:BatchGetItem"
          - "dynamodb:ConditionCheckItem"
          - "dynamodb:PutItem"
          - "dynamodb:DeleteItem"
          - "dynamodb:GetShardIterator"
          - "dynamodb:GetItem"
          - "dynamodb:Scan"
          - "dynamodb:Query"
          - "dynamodb:UpdateItem"
          - "dynamodb:GetRecords"
      Resource: 
        Fn::Join:
          - ":"
          - - arn:aws:dynamodb
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - table/MPFPriceDaily

# Package

package:
  individually: true
  exclude:
    - "**/*"  # quotes(") are needed

# Lambda definition

functions:

  # mpfPriceRetrievalScheduler:
  #   handler: mpf-price-retrieval-scheduler/index.handler
  #   description: The scheduler for MPF price retrieval
  #   memorySize: 128
  #   environment:
  #     RETRIEVE_MPF_PRICE_LAMBDA_ID: ${cf:mpf-price-service.retrieveMPFPriceArn}
  #   package:
  #     include:
  #       - mpf-price-retrieval-scheduler/**   
  #   events:
  #     - schedule:
  #       rate: rate(7 days)
  #       enable: true

  # hello:
  #   handler: hello/index.handler
  #   description: hello test
  #   memorySize: 128
  #   package:
  #     include:
  #       - hello/**
  #   events:
  #     - schedule: 
  #         rate: cron(*/1 * * * ? *)
  #         enabled: true

  retrieveMPFPrice:
    handler: retrieve-mpf-price/index.handler
    description: Retrieve MPF price from API and feed to SQS
    memorySize: 128
    package:
      include:
        - retrieve-mpf-price/**
    events:
      - schedule: 
          rate: cron(0 18 */7 * ? *)
          enabled: true


  saveMPFPriceDynamodb:
    handler: save-mpf-price-dynamodb/index.handler
    description: Save MPF price from SQS to DynamoDB
    memorySize: 128
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - mpfPriceQueue
              - Arn
        batchSize: 10
    package:
      include:
        - save-mpf-price-dynamodb/**

